### PR TITLE
Add server.ListenAddress() : returns server's listen address.

### PR DESCRIPTION
**Pull request by iwanbk**
Useful to get actual listen address when we listen to random port (localhost:0).

Listening to random port is very useful in unit test

Also move the `s.ln=ln` assignment from `serve` to `ListenServeAndSignal` to avoid race condition.

### CODE REVIEW

**Comment by tidwall** [comment]
I’m fine with this change, though could we use the name `Addr` instead of `ListenAddress` and return the `net.Addr` instead of a string?

**Comment by iwanbk** [comment]
> could we use the name Addr instead of ListenAddress and return the net.Addr instead of a string?

sure.

Will change it in next few hours

**Comment by iwanbk** [comment]
> Will change it in next few hours

Done

**Comment by tidwall** [comment]
One more minor thing, could you change the commit message from "Add server.ListenAddress() ..." to "Add server.Addr() ..."?

**Comment by iwanbk** [comment]
> One more minor thing, could you change the commit message from "Add server.ListenAddress() ..." to "Add server.Addr() ..."?

Ah, yeah, my bad, i should did it.
Done

**Pull request merged**
